version: 2.1
jobs:
  compile:
   docker:
      - image: fadlyas/kernel_dockerfile:latest
   steps:
      - run:
          no_output_timeout: 50m
          command: |
            git clone https://github.com/fiqri19102002/android_kernel_xiaomi_mojito.git -b a11/main --depth=1 mojito
            cd mojito
            bash build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
